
module.exports = {

		LOAN_TYPES: ['FIXED_INTEREST', 'REGULAR_INTEREST', 'FULL_FINAL_PAYMENT', 'AMORTIZED'],
	LOAN_STATUSES: ['IN_REVIEW', 'APPROVED', 'DENIED', 'FUNDED', 'OPEN', 'TERMINATED'],
	LOAN_INITIAL_STATUSES: ['IN_REVIEW', 'APPROVED', 'DENIED',],

	TRANSACTION_FLOW_TYPES: ['CREDITED', "DEBITED"],
	TRANSACTION_TYPES: ['INVESTMENT_DEPOSIT', 'INVESTMENT_WITHDRAW']

};